/**
 * Seed data (brief section 12).
 *
 * All of this is fictional. Three rules are deliberate and must not be relaxed:
 *
 *  1. Phone numbers come only from the ranges the ACMA reserves for fictional
 *     use, so nothing here can ever ring a real person:
 *       - Mobiles: ~30 specific numbers in 0491 57x xxx. Only these exact
 *         numbers are reserved — the surrounding block is NOT, so the list
 *         below is used verbatim and never extended by guesswork.
 *       - Victorian landlines: (03) 5550 xxxx and (03) 7010 xxxx are reserved
 *         in full, which is why most contacts here use a landline.
 *     Source: ACMA, "Phone numbers for use in TV shows, films and creative works".
 *  2. Emails are all @example.com, a domain reserved by the IETF for examples.
 *  3. Street names are invented; the suburbs are real Geelong-region suburbs.
 */

import type { FeatureSlug } from "../lib/features.ts";
import type {
  BuyerSource,
  BuyerStatus,
  FinanceStatus,
  ListingStatus,
  PropertyType,
  Timeframe,
} from "../lib/domain.ts";

export const AGENCY_NAME = "Barwon Coast Property";
export const AGENCY_STATE = "VIC";

/* -------------------------------------------------------------------------
 * Suburbs — real Geelong-region suburbs with their real postcodes
 * ---------------------------------------------------------------------- */

export const SUBURBS: Record<string, string> = {
  "Armstrong Creek": "3217",
  Highton: "3216",
  Belmont: "3216",
  Newtown: "3220",
  "Geelong West": "3218",
  Grovedale: "3216",
  "Waurn Ponds": "3216",
  Lara: "3212",
  Leopold: "3224",
  Drysdale: "3222",
  "Ocean Grove": "3226",
  Torquay: "3228",
};

/* -------------------------------------------------------------------------
 * ACMA numbers reserved for fictional use — used verbatim, never extended
 * ---------------------------------------------------------------------- */

export const ACMA_MOBILES = [
  "0491 570 006",
  "0491 570 110",
  "0491 570 156",
  "0491 570 157",
  "0491 570 158",
  "0491 570 159",
  "0491 570 313",
  "0491 570 737",
  "0491 571 266",
  "0491 571 491",
  "0491 571 804",
  "0491 572 549",
  "0491 572 665",
  "0491 572 983",
  "0491 573 087",
  "0491 573 770",
  "0491 574 118",
  "0491 574 632",
  "0491 575 254",
  "0491 575 789",
  "0491 576 398",
  "0491 576 801",
  "0491 577 426",
  "0491 577 644",
  "0491 578 148",
  "0491 578 888",
  "0491 578 957",
  "0491 579 212",
  "0491 579 455",
  "0491 579 760",
];

/** Invented street names. None are real Geelong streets. */
export const STREETS = [
  "Kerrisdale Court",
  "Wattlebird Drive",
  "Tarrangower Street",
  "Bellbrae Rise",
  "Mirradong Way",
  "Quarry Bend",
  "Somerville Grove",
  "Hollybank Place",
  "Ridgemont Avenue",
  "Coledale Street",
  "Pentland Rise",
  "Marrandah Court",
  "Lowanna Drive",
  "Westbury Close",
  "Ferndale Road",
  "Applegum Crescent",
  "Yarrowee Street",
  "Barongarook Way",
  "Melrose Parade",
  "Sandalford Drive",
  "Tullaree Court",
  "Kanooka Grove",
  "Brightmore Street",
  "Cardinia Rise",
  "Heatherlie Avenue",
];

/* -------------------------------------------------------------------------
 * Agents
 * ---------------------------------------------------------------------- */

export const AGENTS = [
  { name: "Marcus Deloraine", email: "marcus.deloraine@example.com" },
  { name: "Priya Raghunathan", email: "priya.raghunathan@example.com" },
  { name: "Tom Kinsella", email: "tom.kinsella@example.com" },
  { name: "Jess Mowbray", email: "jess.mowbray@example.com" },
  { name: "Daniel Okafor", email: "daniel.okafor@example.com" },
  { name: "Alice Brenchley", email: "alice.brenchley@example.com" },
];

/* -------------------------------------------------------------------------
 * Buyers
 * ---------------------------------------------------------------------- */

export type ProfileSpec = {
  name?: string;
  suburbs: string[];
  also?: string[];
  types?: PropertyType[];
  priceMin?: number;
  priceMax?: number;
  stretch?: number;
  beds?: number;
  baths?: number;
  cars?: number;
  landMin?: number;
  landMax?: number;
  must?: FeatureSlug[];
  nice?: FeatureSlug[];
  breakers?: FeatureSlug[];
};

export type BuyerSpec = ProfileSpec & {
  first: string;
  last: string;
  partner?: string;
  brief: string;
  status: BuyerStatus;
  finance: FinanceStatus;
  timeframe: Timeframe;
  source: BuyerSource;
  needsToSell?: boolean;
  /** Days since last contact. Omit with `neverContacted` for a null value. */
  contactedDaysAgo?: number;
  neverContacted?: boolean;
  /** How many days ago the buyer record was created. */
  createdDaysAgo?: number;
  /** Pre-approval expiry, in days from today. Negative means already expired. */
  preApprovalInDays?: number;
  /** An optional second search profile, e.g. a home plus an investment. */
  second?: ProfileSpec;
};

/**
 * Group A — the Highton corridor.
 *
 * Deliberately shaped so the off-market listing at 18 Kerrisdale Court, Highton
 * matches well over ten of them with a genuine spread of scores: some sit dead
 * centre of budget, some only overlap it, some only reach it by stretching,
 * and some fall one bedroom short. That spread is what makes the demo land.
 */
const GROUP_A_HIGHTON: BuyerSpec[] = [
  {
    first: "Nadia",
    last: "Fenwick",
    partner: "Rob",
    brief:
      "Upsizing from Belmont now the third one has arrived. Wants to stay Highton for Montpellier zoning, walk to school is the whole point. Needs a study because Rob works from home three days. Would stretch for something already done up - no renovating with a baby.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "now",
    source: "portal_enquiry",
    needsToSell: true,
    contactedDaysAgo: 4,
    createdDaysAgo: 70,
    preApprovalInDays: 22,
    suburbs: ["Highton"],
    also: ["Newtown"],
    types: ["house"],
    priceMin: 850_000,
    priceMax: 980_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["study", "walk_to_school"],
    nice: ["ensuite", "established_garden"],
    breakers: ["main_road"],
  },
  {
    first: "Douglas",
    last: "Trethowan",
    brief:
      "Retired engineer, very precise about what he wants. Single level only, he's had a knee replacement and won't look at stairs. Wants a shed for the woodwork. Cash from the Newtown sale sitting in the offset.",
    status: "inspecting",
    finance: "cash",
    timeframe: "now",
    source: "walk_in",
    contactedDaysAgo: 2,
    createdDaysAgo: 55,
    suburbs: ["Highton", "Waurn Ponds"],
    types: ["house"],
    priceMin: 800_000,
    priceMax: 950_000,
    beds: 3,
    baths: 2,
    cars: 2,
    landMin: 500,
    must: ["single_level"],
    nice: ["shed_workshop", "established_garden"],
    breakers: ["double_storey"],
  },
  {
    first: "Amelia",
    last: "Kowalczyk",
    partner: "Sam",
    brief:
      "Both work at Deakin so Waurn Ponds or Highton. Four bedrooms, one can be a nursery later. Sam is fussy about north facing living. They've been to about nine opens and haven't offered on anything yet.",
    status: "inspecting",
    finance: "pre_approved",
    timeframe: "within_3_months",
    source: "open_home",
    contactedDaysAgo: 9,
    createdDaysAgo: 95,
    preApprovalInDays: 12,
    suburbs: ["Highton", "Waurn Ponds"],
    also: ["Grovedale"],
    types: ["house", "townhouse"],
    priceMin: 780_000,
    priceMax: 900_000,
    stretch: 960_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["study"],
    nice: ["north_facing", "ensuite"],
  },
  {
    first: "Raj",
    last: "Bhattacharya",
    partner: "Meera",
    brief:
      "Moving down from Melbourne, he's got a role at the hospital starting February. Hasn't sold in Preston yet which is the sticking point. Wants four bedrooms plus a study, ducted heating non negotiable after living in a weatherboard.",
    status: "looking",
    finance: "not_started",
    timeframe: "within_3_months",
    source: "portal_enquiry",
    needsToSell: true,
    contactedDaysAgo: 16,
    createdDaysAgo: 40,
    suburbs: ["Highton", "Newtown"],
    types: ["house"],
    priceMin: 900_000,
    priceMax: 1_100_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["ducted_heating_cooling", "study"],
    nice: ["ensuite", "quiet_street"],
  },
  {
    first: "Fiona",
    last: "Macardle",
    brief:
      "Separated, buying on her own with help from her parents. Budget is genuinely tight but she'd go a bit higher for the right street. Two kids at Highton Primary so she can't move far. Doesn't want a pool, says it's a drowning risk and a chore.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "now",
    source: "referral",
    contactedDaysAgo: 11,
    createdDaysAgo: 48,
    preApprovalInDays: 26,
    suburbs: ["Highton"],
    also: ["Belmont"],
    types: ["house"],
    priceMin: 700_000,
    priceMax: 860_000,
    stretch: 900_000,
    beds: 3,
    baths: 1,
    cars: 1,
    must: ["walk_to_school"],
    nice: ["low_maintenance_yard"],
    breakers: ["pool", "main_road"],
  },
  {
    first: "Geoffrey",
    last: "Ullathorne",
    partner: "Barbara",
    brief:
      "Downsizing off the farm at Inverleigh. Still want a bit of room, Barbara wants her garden. Geoff says he'll only do one level. No rush, they'll wait for the right one, been looking eighteen months.",
    status: "looking",
    finance: "cash",
    timeframe: "within_6_months",
    source: "referral",
    contactedDaysAgo: 74,
    createdDaysAgo: 400,
    suburbs: ["Highton", "Newtown"],
    also: ["Waurn Ponds"],
    types: ["house"],
    priceMin: 850_000,
    priceMax: 1_050_000,
    beds: 3,
    baths: 2,
    cars: 2,
    landMin: 600,
    must: ["single_level", "established_garden"],
    nice: ["shed_workshop"],
  },
  {
    first: "Ciaran",
    last: "O'Loughlin",
    partner: "Steph",
    brief:
      "Second home buyers, outgrown the townhouse in Belmont. Five bedrooms ideally, her mum stays a lot. Steph works from home so a real study not a nook. They'd take something needing paint but not a full reno.",
    status: "inspecting",
    finance: "pre_approved",
    timeframe: "now",
    source: "open_home",
    needsToSell: true,
    contactedDaysAgo: 6,
    createdDaysAgo: 62,
    preApprovalInDays: 8,
    suburbs: ["Highton"],
    also: ["Newtown", "Waurn Ponds"],
    types: ["house"],
    priceMin: 880_000,
    priceMax: 1_000_000,
    beds: 5,
    baths: 2,
    cars: 2,
    must: ["study"],
    nice: ["second_living", "ensuite"],
    breakers: ["needs_renovation"],
  },
  {
    first: "Harriet",
    last: "Vandersluys",
    brief:
      "Buying for her elderly father, he's coming down from Bendigo. Must be single level and close to shops so he can walk. She's the decision maker, he just nods along. Wants it settled before winter.",
    status: "new_enquiry",
    finance: "cash",
    timeframe: "now",
    source: "portal_enquiry",
    contactedDaysAgo: 3,
    createdDaysAgo: 8,
    suburbs: ["Highton", "Belmont"],
    types: ["house", "unit", "townhouse"],
    priceMax: 750_000,
    beds: 2,
    baths: 1,
    cars: 1,
    must: ["single_level", "walk_to_shops"],
    nice: ["low_maintenance_yard"],
    breakers: ["double_storey", "needs_renovation"],
  },
  {
    first: "Patrick",
    last: "Nguyen-Hartley",
    partner: "Bec",
    brief:
      "Both teachers. Pre-approved but it runs out soon and they're getting anxious. Looking Highton or Waurn Ponds, four bedrooms, side access would be great for the camper trailer. Bec mentioned three times she'd love a pool.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "now",
    source: "open_home",
    contactedDaysAgo: 5,
    createdDaysAgo: 44,
    preApprovalInDays: 5,
    suburbs: ["Highton", "Waurn Ponds"],
    types: ["house"],
    priceMin: 820_000,
    priceMax: 930_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["side_access"],
    nice: ["pool", "ducted_heating_cooling"],
  },
  {
    first: "Susan",
    last: "Threlfall",
    brief:
      "Widowed last year, selling the family home in Newtown. Emotional about it so go gently. Wants something easy to look after but still room for the grandkids to stay. Garden is important, she's a keen gardener.",
    status: "looking",
    finance: "cash",
    timeframe: "within_3_months",
    source: "referral",
    needsToSell: true,
    contactedDaysAgo: 21,
    createdDaysAgo: 130,
    suburbs: ["Highton"],
    also: ["Newtown", "Belmont"],
    types: ["house", "townhouse"],
    priceMin: 750_000,
    priceMax: 900_000,
    stretch: 950_000,
    beds: 3,
    baths: 2,
    cars: 1,
    must: ["established_garden"],
    nice: ["single_level", "quiet_street"],
    breakers: ["main_road"],
  },
  {
    first: "Miles",
    last: "Cattanach",
    partner: "Jo",
    brief:
      "Coming back from Perth after six years. Know the area well, grew up in Belmont. Want four bedrooms and a decent block, Miles is a tradie and needs somewhere for the ute and trailer. Quiet street matters, they're over main road living.",
    status: "new_enquiry",
    finance: "pre_approved",
    timeframe: "within_3_months",
    source: "portal_enquiry",
    contactedDaysAgo: 7,
    createdDaysAgo: 12,
    preApprovalInDays: 40,
    suburbs: ["Highton", "Belmont", "Grovedale"],
    types: ["house"],
    priceMin: 780_000,
    priceMax: 920_000,
    beds: 4,
    baths: 2,
    cars: 2,
    landMin: 550,
    must: ["side_access", "quiet_street"],
    nice: ["shed_workshop", "garage"],
    breakers: ["main_road"],
  },
  {
    first: "Yvette",
    last: "Brannigan",
    brief:
      "Very organised, spreadsheet and all. Wants Highton but would consider Newtown for the right place. Four bed minimum, ensuite essential, she was clear about that. Doesn't care about land size, hates mowing.",
    status: "inspecting",
    finance: "pre_approved",
    timeframe: "now",
    source: "open_home",
    contactedDaysAgo: 1,
    createdDaysAgo: 33,
    preApprovalInDays: 55,
    suburbs: ["Highton"],
    also: ["Newtown"],
    types: ["house", "townhouse"],
    priceMin: 860_000,
    priceMax: 1_020_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["ensuite"],
    nice: ["low_maintenance_yard", "study"],
  },
  {
    first: "Hamish",
    last: "Pilkington",
    partner: "Ruth",
    brief:
      "Investor turned owner occupier. Already has two units in Grovedale. Now wants a family home for themselves but keeps thinking like an investor, always asking about rental yield. Needs convincing on emotion.",
    status: "new_enquiry",
    finance: "pre_approved",
    timeframe: "within_6_months",
    source: "database_import",
    contactedDaysAgo: 19,
    createdDaysAgo: 25,
    preApprovalInDays: 70,
    suburbs: ["Highton", "Waurn Ponds"],
    also: ["Grovedale", "Belmont"],
    types: ["house"],
    priceMin: 800_000,
    priceMax: 940_000,
    beds: 4,
    baths: 2,
    cars: 2,
    nice: ["ducted_heating_cooling", "garage"],
    second: {
      name: "Investment",
      suburbs: ["Grovedale", "Belmont", "Armstrong Creek"],
      types: ["unit", "townhouse"],
      priceMin: 400_000,
      priceMax: 560_000,
      beds: 2,
      baths: 1,
      nice: ["low_maintenance_yard", "garage"],
    },
  },
  {
    first: "Linh",
    last: "Tran-Whitmore",
    partner: "Ed",
    brief:
      "Expecting twins in March so there's a hard deadline. Need four bedrooms minimum and they want it move in ready. Ed's parents are helping with the deposit. Linh said absolutely no main road, she's thinking about the kids.",
    status: "offer_made",
    finance: "pre_approved",
    timeframe: "now",
    source: "open_home",
    contactedDaysAgo: 1,
    createdDaysAgo: 50,
    preApprovalInDays: 18,
    suburbs: ["Highton", "Waurn Ponds", "Grovedale"],
    types: ["house"],
    priceMin: 830_000,
    priceMax: 960_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["renovated"],
    nice: ["ensuite", "second_living"],
    breakers: ["main_road", "needs_renovation"],
  },
  {
    first: "Brett",
    last: "Sanderson-Hoyle",
    brief:
      "Pushy, rings a lot. Says he'll pay over the odds for the right thing in Highton but his finance says otherwise. Six bedrooms he reckons, for the blended family. Manage expectations here.",
    status: "looking",
    finance: "not_started",
    timeframe: "now",
    source: "walk_in",
    contactedDaysAgo: 2,
    createdDaysAgo: 20,
    suburbs: ["Highton"],
    types: ["house"],
    priceMin: 900_000,
    priceMax: 1_050_000,
    beds: 6,
    baths: 3,
    cars: 3,
    nice: ["second_living", "pool"],
  },
  {
    first: "Wendy",
    last: "Charlesworth",
    brief:
      "Lovely but hasn't been contacted in months, fell through the cracks when Dave left. Was looking Highton area, three or four bedrooms, mid eights. Worth a call to see if she's still in the market.",
    status: "looking",
    finance: "unknown",
    timeframe: "unknown",
    source: "database_import",
    contactedDaysAgo: 96,
    createdDaysAgo: 210,
    suburbs: ["Highton", "Belmont"],
    types: ["house"],
    priceMin: 750_000,
    priceMax: 890_000,
    beds: 3,
    baths: 1,
    cars: 1,
    nice: ["garage"],
  },
];

/** Group B — coastal: Ocean Grove, Torquay, Drysdale, Leopold. */
const GROUP_B_COASTAL: BuyerSpec[] = [
  {
    first: "Callum",
    last: "Fetherstonhaugh",
    partner: "Tess",
    brief:
      "Sea change from Carlton. Both work remote so they can go anywhere with decent internet. Walk to the beach is the dream, Tess said she wants to hear the surf. Budget is healthy, they sold well in Melbourne.",
    status: "inspecting",
    finance: "cash",
    timeframe: "now",
    source: "portal_enquiry",
    contactedDaysAgo: 3,
    createdDaysAgo: 36,
    suburbs: ["Ocean Grove", "Torquay"],
    types: ["house"],
    priceMin: 1_100_000,
    priceMax: 1_500_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["walk_to_beach", "home_office"],
    nice: ["water_views", "north_facing"],
  },
  {
    first: "Gemma",
    last: "Ashbolt",
    brief:
      "Buying a holiday place that'll become the retirement house. Torquay only, she's very set on it. Low maintenance because it'll sit empty half the year. No garden to speak of, she doesn't want the upkeep.",
    status: "looking",
    finance: "cash",
    timeframe: "within_6_months",
    source: "referral",
    contactedDaysAgo: 34,
    createdDaysAgo: 160,
    suburbs: ["Torquay"],
    types: ["house", "townhouse", "unit"],
    priceMin: 850_000,
    priceMax: 1_200_000,
    beds: 3,
    baths: 2,
    cars: 1,
    must: ["low_maintenance_yard"],
    nice: ["walk_to_beach", "walk_to_shops"],
    breakers: ["needs_renovation"],
  },
  {
    first: "Wayne",
    last: "Bartholomew",
    partner: "Kaz",
    brief:
      "Retiring in about a year, want to be settled in Drysdale near Kaz's sister. Big shed is the main thing for Wayne, he's got a boat and two motorbikes. Happy to be a bit out of town for more land.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "within_6_months",
    source: "open_home",
    needsToSell: true,
    contactedDaysAgo: 28,
    createdDaysAgo: 140,
    preApprovalInDays: 21,
    suburbs: ["Drysdale", "Leopold"],
    types: ["house", "acreage"],
    priceMin: 750_000,
    priceMax: 950_000,
    beds: 3,
    baths: 2,
    cars: 3,
    landMin: 800,
    must: ["shed_workshop", "side_access"],
    nice: ["single_level", "solar"],
  },
  {
    first: "Danielle",
    last: "Corrigan",
    brief:
      "First home buyer, saved hard, works at the hospital. Ocean Grove because her family's there. Budget is what it is, she knows she might have to compromise on the beach walk.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "within_3_months",
    source: "portal_enquiry",
    contactedDaysAgo: 13,
    createdDaysAgo: 58,
    preApprovalInDays: 29,
    suburbs: ["Ocean Grove"],
    also: ["Leopold", "Drysdale"],
    types: ["house", "townhouse", "unit"],
    priceMax: 720_000,
    beds: 2,
    baths: 1,
    cars: 1,
    nice: ["walk_to_shops", "low_maintenance_yard"],
  },
  {
    first: "Stefan",
    last: "Mihailovic",
    partner: "Anna",
    brief:
      "Want a place the whole extended family can descend on at Christmas. Five bedrooms if possible, or four and a decent second living. Pool would be a huge tick, the kids are teenagers.",
    status: "inspecting",
    finance: "pre_approved",
    timeframe: "now",
    source: "open_home",
    needsToSell: true,
    contactedDaysAgo: 8,
    createdDaysAgo: 72,
    preApprovalInDays: 47,
    suburbs: ["Ocean Grove", "Torquay"],
    also: ["Drysdale"],
    types: ["house"],
    priceMin: 1_000_000,
    priceMax: 1_350_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["second_living"],
    nice: ["pool", "walk_to_beach"],
  },
  {
    first: "Josephine",
    last: "Lacksworth",
    brief:
      "Downsizer from a big place at Barwon Heads. Wants to stay coastal but smaller. Very particular about light, mentioned north facing about five times.",
    status: "new_enquiry",
    finance: "cash",
    timeframe: "within_3_months",
    source: "walk_in",
    needsToSell: true,
    contactedDaysAgo: 6,
    createdDaysAgo: 10,
    suburbs: ["Ocean Grove"],
    also: ["Torquay"],
    types: ["house", "townhouse"],
    priceMin: 800_000,
    priceMax: 1_100_000,
    beds: 3,
    baths: 2,
    cars: 2,
    must: ["north_facing", "single_level"],
    nice: ["established_garden", "walk_to_shops"],
  },
  {
    first: "Trent",
    last: "Whitburn",
    brief:
      "Surf coast lifestyle buyer, works fly in fly out so he's away a lot. Wants something secure and low maintenance he can lock up and leave. Not fussed about bedrooms.",
    status: "paused",
    finance: "pre_approved",
    timeframe: "just_looking",
    source: "portal_enquiry",
    contactedDaysAgo: 42,
    createdDaysAgo: 180,
    preApprovalInDays: -14,
    suburbs: ["Torquay"],
    types: ["townhouse", "unit"],
    priceMin: 650_000,
    priceMax: 900_000,
    beds: 2,
    baths: 1,
    cars: 1,
    must: ["low_maintenance_yard"],
    nice: ["garage", "walk_to_beach"],
  },
  {
    first: "Bridie",
    last: "O'Halloran",
    partner: "Marcus",
    brief:
      "Young family, both grew up in Ocean Grove and want to raise the kids there. Tight budget so they're realistic about needing to do work. Marcus is handy, says he'll renovate over time.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "within_3_months",
    source: "open_home",
    contactedDaysAgo: 17,
    createdDaysAgo: 66,
    preApprovalInDays: 35,
    suburbs: ["Ocean Grove"],
    also: ["Leopold"],
    types: ["house"],
    priceMin: 620_000,
    priceMax: 800_000,
    stretch: 850_000,
    beds: 3,
    baths: 1,
    cars: 1,
    nice: ["side_access", "shed_workshop"],
  },
  {
    first: "Anthony",
    last: "Pellegrino",
    brief:
      "Bought at Ocean Grove through us in March, settled and happy. Keep on file, he mentioned wanting an investment down the track.",
    status: "purchased",
    finance: "cash",
    timeframe: "just_looking",
    source: "referral",
    contactedDaysAgo: 40,
    createdDaysAgo: 300,
    suburbs: ["Ocean Grove"],
    types: ["house"],
    priceMin: 900_000,
    priceMax: 1_200_000,
    beds: 3,
  },
  {
    first: "Kirsten",
    last: "Ravenhill",
    brief:
      "Wanted Torquay under a million which just wasn't happening. Ended up buying privately at Jan Juc. Closed out but worth keeping warm, she's got family looking too.",
    status: "bought_elsewhere",
    finance: "pre_approved",
    timeframe: "just_looking",
    source: "portal_enquiry",
    contactedDaysAgo: 55,
    createdDaysAgo: 220,
    suburbs: ["Torquay"],
    types: ["house"],
    priceMax: 1_000_000,
    beds: 3,
  },
  {
    first: "Dev",
    last: "Ramanathan",
    partner: "Priya",
    brief:
      "Looking Leopold or Drysdale for the value. Both commute to Geelong. Want four bedrooms and a double garage. Solar is a big thing for them, they're conscious about running costs.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "within_3_months",
    source: "portal_enquiry",
    contactedDaysAgo: 12,
    createdDaysAgo: 52,
    preApprovalInDays: 62,
    suburbs: ["Leopold", "Drysdale"],
    also: ["Grovedale"],
    types: ["house"],
    priceMin: 650_000,
    priceMax: 820_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["garage"],
    nice: ["solar", "ducted_heating_cooling"],
    second: {
      name: "Investment",
      suburbs: ["Leopold", "Grovedale"],
      types: ["unit", "townhouse"],
      priceMax: 550_000,
      beds: 2,
      baths: 1,
      nice: ["garage", "low_maintenance_yard"],
    },
  },
  {
    first: "Maureen",
    last: "Stackpoole",
    brief:
      "Elderly, quite deaf on the phone so email her. Selling in Leopold, wants a unit near the shops. Single level absolutely essential.",
    status: "new_enquiry",
    finance: "cash",
    timeframe: "within_6_months",
    source: "walk_in",
    needsToSell: true,
    contactedDaysAgo: 9,
    createdDaysAgo: 14,
    suburbs: ["Leopold", "Drysdale"],
    types: ["unit", "townhouse"],
    priceMax: 600_000,
    beds: 2,
    baths: 1,
    cars: 1,
    must: ["single_level", "walk_to_shops"],
    breakers: ["double_storey"],
  },
  {
    first: "Craig",
    last: "Newbould",
    brief:
      "Enquired on a Drysdale listing months ago, never picked up since. Details are thin. Someone should try him.",
    status: "new_enquiry",
    finance: "unknown",
    timeframe: "unknown",
    source: "portal_enquiry",
    neverContacted: true,
    createdDaysAgo: 88,
    suburbs: ["Drysdale"],
    types: ["house"],
    priceMax: 800_000,
  },
  {
    first: "Elena",
    last: "Vasilenko",
    brief:
      "Investor from Sydney, never seen the area. Wants numbers not photos. Looking for anything under 600 that rents well. Talks about yield constantly.",
    status: "looking",
    finance: "cash",
    timeframe: "now",
    source: "database_import",
    contactedDaysAgo: 25,
    createdDaysAgo: 90,
    suburbs: ["Leopold", "Grovedale", "Belmont", "Armstrong Creek"],
    types: ["unit", "townhouse"],
    priceMax: 600_000,
    beds: 2,
    nice: ["low_maintenance_yard", "garage"],
    breakers: ["needs_renovation"],
  },
];

/** Group C — entry level and first home buyers. */
const GROUP_C_ENTRY: BuyerSpec[] = [
  {
    first: "Jordan",
    last: "Whitcombe",
    partner: "Ash",
    brief:
      "First home buyers, both in their twenties. Armstrong Creek makes sense for the price and it's all new. They want something they don't have to touch. Ash wants a proper garage not a carport.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "now",
    source: "open_home",
    contactedDaysAgo: 5,
    createdDaysAgo: 30,
    preApprovalInDays: 24,
    suburbs: ["Armstrong Creek"],
    also: ["Grovedale", "Leopold"],
    types: ["house", "townhouse"],
    priceMin: 550_000,
    priceMax: 700_000,
    beds: 3,
    baths: 2,
    cars: 2,
    must: ["garage"],
    nice: ["ducted_heating_cooling", "low_maintenance_yard"],
    breakers: ["needs_renovation", "main_road"],
  },
  {
    first: "Tayla",
    last: "Bruckner",
    brief:
      "Single buyer, nurse at Barwon Health, does shift work so ring her afternoons. Belmont or Grovedale. Doesn't want a big yard, hasn't got the time.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "within_3_months",
    source: "portal_enquiry",
    contactedDaysAgo: 20,
    createdDaysAgo: 75,
    preApprovalInDays: 16,
    suburbs: ["Belmont", "Grovedale"],
    types: ["house", "townhouse", "unit"],
    priceMax: 650_000,
    beds: 2,
    baths: 1,
    cars: 1,
    nice: ["low_maintenance_yard", "garage"],
  },
  {
    first: "Sione",
    last: "Tuilagi",
    partner: "Mele",
    brief:
      "Big family, five kids. Need bedrooms more than anything, four minimum but five would be better. Budget is stretched. Grovedale or Armstrong Creek. Mele's mum might move in eventually so a granny flat would be gold.",
    status: "looking",
    finance: "not_started",
    timeframe: "within_3_months",
    source: "walk_in",
    contactedDaysAgo: 14,
    createdDaysAgo: 46,
    suburbs: ["Grovedale", "Armstrong Creek"],
    also: ["Belmont"],
    types: ["house"],
    priceMax: 750_000,
    beds: 4,
    baths: 2,
    cars: 2,
    nice: ["granny_flat", "second_living"],
  },
  {
    first: "Alyssa",
    last: "Pemberton",
    brief:
      "Enquired at an open home, seemed keen but hasn't returned calls since. Was after a townhouse in Belmont under six.",
    status: "new_enquiry",
    finance: "unknown",
    timeframe: "unknown",
    source: "open_home",
    neverContacted: true,
    createdDaysAgo: 31,
    suburbs: ["Belmont"],
    types: ["townhouse", "unit"],
    priceMax: 600_000,
    beds: 2,
  },
  {
    first: "Nathan",
    last: "Oldacre",
    brief:
      "Young tradie, buying alone. Wants land and a shed more than a nice kitchen. Happy with something rough he can do up himself. Lara or Armstrong Creek for the block size.",
    status: "inspecting",
    finance: "pre_approved",
    timeframe: "now",
    source: "open_home",
    contactedDaysAgo: 4,
    createdDaysAgo: 38,
    preApprovalInDays: 33,
    suburbs: ["Lara", "Armstrong Creek"],
    also: ["Grovedale"],
    types: ["house"],
    priceMax: 700_000,
    beds: 3,
    cars: 2,
    landMin: 500,
    must: ["side_access"],
    nice: ["shed_workshop", "needs_renovation"],
  },
  {
    first: "Chloe",
    last: "Hardwicke",
    partner: "Sam",
    brief:
      "Renting in Newtown and priced out of it. Reluctantly looking at Belmont. Sam commutes to Melbourne so walk to the station would change their life.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "within_3_months",
    source: "portal_enquiry",
    contactedDaysAgo: 18,
    createdDaysAgo: 61,
    preApprovalInDays: 27,
    suburbs: ["Belmont", "Geelong West"],
    also: ["Grovedale"],
    types: ["house", "townhouse"],
    priceMin: 600_000,
    priceMax: 780_000,
    beds: 3,
    baths: 1,
    cars: 1,
    nice: ["walk_to_station", "renovated"],
    breakers: ["main_road"],
  },
  {
    first: "Ibrahim",
    last: "Kacar",
    brief:
      "Buying with his brother as an investment and for his brother to live in. Complicated ownership talk, get the finance clear early. Lara area.",
    status: "new_enquiry",
    finance: "not_started",
    timeframe: "within_6_months",
    source: "referral",
    contactedDaysAgo: 11,
    createdDaysAgo: 18,
    suburbs: ["Lara"],
    also: ["Armstrong Creek"],
    types: ["house", "townhouse"],
    priceMax: 680_000,
    beds: 3,
    baths: 1,
    cars: 1,
  },
  {
    first: "Rebecca",
    last: "Stanislaus",
    brief:
      "Was looking Grovedale for months, went quiet. Her circumstances changed apparently. Paused for now, wants a call in the new year.",
    status: "paused",
    finance: "not_started",
    timeframe: "just_looking",
    source: "open_home",
    contactedDaysAgo: 38,
    createdDaysAgo: 190,
    suburbs: ["Grovedale"],
    types: ["house"],
    priceMax: 700_000,
    beds: 3,
  },
  {
    first: "Lachlan",
    last: "Merriweather",
    partner: "Zoe",
    brief:
      "Made an offer on the Grovedale place, waiting on their finance. Fingers crossed. They're lovely, would be great to get them through.",
    status: "offer_made",
    finance: "pre_approved",
    timeframe: "now",
    source: "open_home",
    contactedDaysAgo: 1,
    createdDaysAgo: 42,
    preApprovalInDays: 19,
    suburbs: ["Grovedale", "Armstrong Creek"],
    types: ["house"],
    priceMin: 600_000,
    priceMax: 730_000,
    beds: 3,
    baths: 2,
    cars: 2,
    nice: ["garage", "low_maintenance_yard"],
  },
  {
    first: "Priyanka",
    last: "Deshmukh",
    brief:
      "Under contract on the Armstrong Creek townhouse, settling next month. All going smoothly.",
    status: "under_contract",
    finance: "pre_approved",
    timeframe: "now",
    source: "portal_enquiry",
    contactedDaysAgo: 2,
    createdDaysAgo: 80,
    preApprovalInDays: 90,
    suburbs: ["Armstrong Creek"],
    types: ["townhouse"],
    priceMax: 620_000,
    beds: 3,
    baths: 2,
  },
  {
    first: "Owen",
    last: "Fairweather",
    brief:
      "Decided to keep renting and travel instead. Nice bloke, might be back in a couple of years.",
    status: "not_proceeding",
    finance: "not_started",
    timeframe: "just_looking",
    source: "walk_in",
    contactedDaysAgo: 60,
    createdDaysAgo: 240,
    suburbs: ["Belmont"],
    types: ["unit"],
    priceMax: 500_000,
    beds: 1,
  },
  {
    first: "Sarah-Jane",
    last: "Colquhoun",
    brief:
      "Old database record, no contact for ages. Was after a first home in Lara. Probably cold but worth one try.",
    status: "looking",
    finance: "unknown",
    timeframe: "unknown",
    source: "database_import",
    contactedDaysAgo: 145,
    createdDaysAgo: 400,
    suburbs: ["Lara"],
    types: ["house"],
    priceMax: 650_000,
    beds: 3,
  },
  {
    first: "Marco",
    last: "Ferrante",
    partner: "Gina",
    brief:
      "Older couple, want to be near their daughter in Grovedale. Downsizing from Werribee. Single level, small yard, close to shops. Gina doesn't drive so that matters.",
    status: "looking",
    finance: "cash",
    timeframe: "within_3_months",
    source: "referral",
    needsToSell: true,
    contactedDaysAgo: 23,
    createdDaysAgo: 100,
    suburbs: ["Grovedale", "Belmont"],
    types: ["house", "unit", "townhouse"],
    priceMax: 680_000,
    beds: 2,
    baths: 1,
    cars: 1,
    must: ["single_level", "walk_to_shops"],
    nice: ["low_maintenance_yard"],
    breakers: ["double_storey"],
  },
  {
    first: "Hayley",
    last: "Tsiolkas",
    brief:
      "Came through an open home at Armstrong Creek. Keen, young, first home. Hasn't sorted finance yet which is the hold up.",
    status: "new_enquiry",
    finance: "not_started",
    timeframe: "within_3_months",
    source: "open_home",
    contactedDaysAgo: 4,
    createdDaysAgo: 6,
    suburbs: ["Armstrong Creek"],
    types: ["house", "townhouse"],
    priceMax: 660_000,
    beds: 3,
    baths: 2,
    nice: ["garage"],
  },
  {
    first: "Grant",
    last: "Purslowe",
    brief:
      "Wants a project. Genuinely looking for the worst house in a good street. Has done two before so he knows what he's in for.",
    status: "looking",
    finance: "cash",
    timeframe: "now",
    source: "referral",
    contactedDaysAgo: 15,
    createdDaysAgo: 85,
    suburbs: ["Belmont", "Geelong West", "Newtown"],
    types: ["house"],
    priceMax: 800_000,
    beds: 2,
    landMin: 450,
    must: ["needs_renovation"],
    nice: ["corner_block", "side_access"],
    breakers: ["renovated"],
  },
  {
    first: "Monique",
    last: "Beauchamp",
    brief:
      "Enquiry from the portal, wanted Lara. Never managed to reach her, number might be wrong. Try the email.",
    status: "new_enquiry",
    finance: "unknown",
    timeframe: "unknown",
    source: "portal_enquiry",
    neverContacted: true,
    createdDaysAgo: 24,
    suburbs: ["Lara"],
    types: ["house"],
    priceMax: 700_000,
    beds: 3,
  },
  {
    first: "Declan",
    last: "Mulqueeney",
    partner: "Sinead",
    brief:
      "Irish, over on visas, just got permanent residency so they can finally buy. Very excited. Lara because his work is at Avalon. Want a bit of land for a veggie patch.",
    status: "inspecting",
    finance: "pre_approved",
    timeframe: "now",
    source: "walk_in",
    contactedDaysAgo: 7,
    createdDaysAgo: 34,
    preApprovalInDays: 44,
    suburbs: ["Lara"],
    also: ["Armstrong Creek"],
    types: ["house"],
    priceMin: 580_000,
    priceMax: 740_000,
    beds: 3,
    baths: 2,
    cars: 2,
    landMin: 450,
    nice: ["shed_workshop", "established_garden"],
  },
  {
    first: "Bianca",
    last: "Wrightson",
    brief:
      "Bought elsewhere through another agency, was pretty blunt about it. Record kept for completeness.",
    status: "bought_elsewhere",
    finance: "pre_approved",
    timeframe: "just_looking",
    source: "portal_enquiry",
    contactedDaysAgo: 70,
    createdDaysAgo: 200,
    suburbs: ["Grovedale"],
    types: ["house"],
    priceMax: 700_000,
    beds: 3,
  },
  {
    first: "Aaron",
    last: "Kirkbride",
    brief:
      "Settled on the Belmont house in June. Happy customer, sent us two referrals already.",
    status: "purchased",
    finance: "pre_approved",
    timeframe: "just_looking",
    source: "referral",
    contactedDaysAgo: 35,
    createdDaysAgo: 280,
    suburbs: ["Belmont"],
    types: ["house"],
    priceMax: 780_000,
    beds: 3,
  },
  {
    first: "Nicola",
    last: "Aitchison",
    brief:
      "Lost her job mid search so she's put it on hold. Was pre-approved but that's expired now. Sensitive, don't push.",
    status: "paused",
    finance: "not_started",
    timeframe: "unknown",
    source: "open_home",
    contactedDaysAgo: 47,
    createdDaysAgo: 170,
    preApprovalInDays: -30,
    suburbs: ["Belmont", "Grovedale"],
    types: ["house", "townhouse"],
    priceMax: 700_000,
    beds: 3,
  },
];

/** Group D — premium: Newtown, Geelong West. */
const GROUP_D_PREMIUM: BuyerSpec[] = [
  {
    first: "Edwina",
    last: "Marchetti",
    partner: "Julian",
    brief:
      "Want a period home in Newtown, properly restored not flipped. Julian is an architect so he notices everything. They've walked away from three because the renovations were poor quality. Patient buyers.",
    status: "looking",
    finance: "cash",
    timeframe: "within_6_months",
    source: "referral",
    contactedDaysAgo: 26,
    createdDaysAgo: 150,
    suburbs: ["Newtown"],
    also: ["Geelong West"],
    types: ["house"],
    priceMin: 1_400_000,
    priceMax: 2_000_000,
    beds: 4,
    baths: 2,
    cars: 2,
    landMin: 600,
    must: ["renovated", "established_garden"],
    nice: ["north_facing", "quiet_street"],
    breakers: ["main_road", "needs_renovation"],
  },
  {
    first: "Dr Alistair",
    last: "Fanshawe",
    brief:
      "Surgeon, relocating from Adelaide. Time poor, wants options sent to him rather than browsing. Newtown or Geelong West, four bed plus study, walk to the hospital ideally.",
    status: "new_enquiry",
    finance: "pre_approved",
    timeframe: "now",
    source: "portal_enquiry",
    contactedDaysAgo: 2,
    createdDaysAgo: 9,
    preApprovalInDays: 58,
    suburbs: ["Newtown", "Geelong West"],
    types: ["house"],
    priceMin: 1_200_000,
    priceMax: 1_700_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["study"],
    nice: ["ensuite", "renovated"],
  },
  {
    first: "Rosalind",
    last: "Kentish",
    brief:
      "Long time Newtown resident downsizing within the suburb. Knows every street and has opinions on all of them. Won't consider anything on Pakington end, too noisy.",
    status: "looking",
    finance: "cash",
    timeframe: "within_3_months",
    source: "walk_in",
    needsToSell: true,
    contactedDaysAgo: 31,
    createdDaysAgo: 120,
    suburbs: ["Newtown"],
    types: ["house", "townhouse"],
    priceMin: 900_000,
    priceMax: 1_250_000,
    beds: 3,
    baths: 2,
    cars: 1,
    must: ["quiet_street"],
    nice: ["single_level", "established_garden"],
    breakers: ["main_road"],
  },
  {
    first: "Simon",
    last: "Vandenberg",
    partner: "Kate",
    brief:
      "Selling in Melbourne, big budget, want the best they can get in Geelong West. Kate wants a pool, Simon says it's a waste. They'll work it out.",
    status: "inspecting",
    finance: "pre_approved",
    timeframe: "now",
    source: "portal_enquiry",
    needsToSell: true,
    contactedDaysAgo: 3,
    createdDaysAgo: 39,
    preApprovalInDays: 37,
    suburbs: ["Geelong West", "Newtown"],
    types: ["house"],
    priceMin: 1_100_000,
    priceMax: 1_500_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["renovated"],
    nice: ["pool", "second_living"],
  },
  {
    first: "Annabel",
    last: "Cresswell-Hume",
    brief:
      "Buying a second property in Geelong West to be near the grandchildren. Wants something manageable, she's only here half the year.",
    status: "looking",
    finance: "cash",
    timeframe: "within_6_months",
    source: "referral",
    contactedDaysAgo: 65,
    createdDaysAgo: 230,
    suburbs: ["Geelong West"],
    also: ["Newtown"],
    types: ["townhouse", "unit"],
    priceMin: 700_000,
    priceMax: 950_000,
    beds: 2,
    baths: 2,
    cars: 1,
    must: ["low_maintenance_yard"],
    nice: ["walk_to_shops", "walk_to_station"],
  },
  {
    first: "Peter",
    last: "Wollaston",
    brief:
      "Under contract on the Newtown period home. Long settlement at his request. Everything on track.",
    status: "under_contract",
    finance: "cash",
    timeframe: "now",
    source: "open_home",
    contactedDaysAgo: 5,
    createdDaysAgo: 110,
    suburbs: ["Newtown"],
    types: ["house"],
    priceMin: 1_300_000,
    priceMax: 1_800_000,
    beds: 4,
  },
  {
    first: "Louise",
    last: "Sanderson",
    partner: "Tim",
    brief:
      "Wanted Newtown but their budget kept getting beaten. Frustrated. Considering Geelong West now instead. Tim's losing patience with the process.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "now",
    source: "open_home",
    contactedDaysAgo: 10,
    createdDaysAgo: 140,
    preApprovalInDays: 11,
    suburbs: ["Geelong West"],
    also: ["Newtown", "Belmont"],
    types: ["house"],
    priceMin: 850_000,
    priceMax: 1_050_000,
    stretch: 1_150_000,
    beds: 3,
    baths: 2,
    cars: 1,
    nice: ["renovated", "walk_to_shops"],
  },
  {
    first: "Gregory",
    last: "Ashwood-Pike",
    brief:
      "Old record, was after a premium Newtown home years back. No contact in a very long time. Almost certainly cold.",
    status: "looking",
    finance: "unknown",
    timeframe: "unknown",
    source: "database_import",
    contactedDaysAgo: 210,
    createdDaysAgo: 500,
    suburbs: ["Newtown"],
    types: ["house"],
    priceMin: 1_000_000,
    priceMax: 1_600_000,
    beds: 4,
  },
  {
    first: "Meredith",
    last: "Calthorpe",
    brief:
      "Decided against moving after all, staying put. Was quite apologetic about it.",
    status: "not_proceeding",
    finance: "cash",
    timeframe: "just_looking",
    source: "referral",
    contactedDaysAgo: 52,
    createdDaysAgo: 210,
    suburbs: ["Newtown"],
    types: ["house"],
    priceMax: 1_400_000,
    beds: 3,
  },
  {
    first: "Xavier",
    last: "Beaumont-Lisle",
    partner: "Claudia",
    brief:
      "Want a statement home. Pool, second living, the lot. Newtown or the good end of Geelong West. Budget is real, they've sold already and are renting.",
    status: "inspecting",
    finance: "cash",
    timeframe: "now",
    source: "portal_enquiry",
    contactedDaysAgo: 6,
    createdDaysAgo: 48,
    suburbs: ["Newtown", "Geelong West"],
    types: ["house"],
    priceMin: 1_500_000,
    priceMax: 2_200_000,
    beds: 5,
    baths: 3,
    cars: 2,
    must: ["pool", "second_living"],
    nice: ["ensuite", "renovated", "north_facing"],
  },
  {
    first: "Helena",
    last: "Ostrowski",
    brief:
      "Bought in Newtown in April. Delighted. Has already referred her sister to us.",
    status: "purchased",
    finance: "cash",
    timeframe: "just_looking",
    source: "open_home",
    contactedDaysAgo: 48,
    createdDaysAgo: 310,
    suburbs: ["Newtown"],
    types: ["house"],
    priceMax: 1_500_000,
    beds: 4,
  },
  {
    first: "Roland",
    last: "Twycross",
    brief:
      "Investor buying in Geelong West for the land value, long term hold. Doesn't care about condition at all, only the block.",
    status: "looking",
    finance: "cash",
    timeframe: "within_6_months",
    source: "database_import",
    contactedDaysAgo: 81,
    createdDaysAgo: 260,
    suburbs: ["Geelong West", "Newtown"],
    types: ["house", "land"],
    priceMax: 1_100_000,
    landMin: 600,
    nice: ["corner_block", "side_access"],
    second: {
      name: "Coastal hold",
      suburbs: ["Ocean Grove", "Drysdale"],
      types: ["house"],
      priceMax: 950_000,
      beds: 3,
      landMin: 500,
      nice: ["side_access", "shed_workshop"],
    },
  },
];

/** Group E — the rest: mixed, filling out the pipeline and the stale list. */
const GROUP_E_MIXED: BuyerSpec[] = [
  {
    first: "Katrina",
    last: "Boddington",
    brief:
      "Enquired months ago on a Waurn Ponds listing, nobody's followed up. Was after a family home mid sevens. Should be an easy re-engage.",
    status: "looking",
    finance: "unknown",
    timeframe: "unknown",
    source: "portal_enquiry",
    contactedDaysAgo: 110,
    createdDaysAgo: 250,
    suburbs: ["Waurn Ponds", "Grovedale"],
    types: ["house"],
    priceMin: 680_000,
    priceMax: 800_000,
    beds: 4,
    baths: 2,
    cars: 2,
  },
  {
    first: "Vikram",
    last: "Seshadri",
    partner: "Anjali",
    brief:
      "Deakin academics, want to walk to campus. Four bedrooms, one as a study each. Solar matters to them, they're quite green.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "within_3_months",
    source: "open_home",
    contactedDaysAgo: 8,
    createdDaysAgo: 56,
    preApprovalInDays: 41,
    suburbs: ["Waurn Ponds", "Highton"],
    types: ["house"],
    priceMin: 750_000,
    priceMax: 900_000,
    beds: 4,
    baths: 2,
    cars: 2,
    must: ["study", "solar"],
    nice: ["ducted_heating_cooling", "north_facing"],
  },
  {
    first: "Shane",
    last: "Corbould",
    brief:
      "Wants a shed. That's basically the brief. House is secondary. Anywhere with a big block and side access.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "now",
    source: "walk_in",
    contactedDaysAgo: 13,
    createdDaysAgo: 44,
    preApprovalInDays: 50,
    suburbs: ["Lara", "Leopold", "Drysdale"],
    also: ["Grovedale", "Armstrong Creek"],
    types: ["house", "acreage"],
    priceMax: 850_000,
    beds: 3,
    cars: 3,
    landMin: 700,
    must: ["shed_workshop", "side_access"],
    nice: ["single_level"],
  },
  {
    first: "Petra",
    last: "Lindqvist",
    brief:
      "Swedish, here for work, may or may not stay long term. Cautious buyer, lots of questions about the market. Wants something low risk and easy to resell.",
    status: "new_enquiry",
    finance: "not_started",
    timeframe: "within_6_months",
    source: "portal_enquiry",
    contactedDaysAgo: 5,
    createdDaysAgo: 11,
    suburbs: ["Newtown", "Geelong West", "Highton"],
    types: ["townhouse", "unit"],
    priceMax: 750_000,
    beds: 2,
    baths: 1,
    nice: ["walk_to_shops", "renovated"],
  },
  {
    first: "Duncan",
    last: "Thorburn",
    partner: "Lisa",
    brief:
      "Made an offer on the Waurn Ponds house, it was knocked back. Disappointed but still very much in the market. Move quickly if something similar comes up.",
    status: "offer_made",
    finance: "pre_approved",
    timeframe: "now",
    source: "open_home",
    contactedDaysAgo: 2,
    createdDaysAgo: 51,
    preApprovalInDays: 14,
    suburbs: ["Waurn Ponds", "Highton", "Grovedale"],
    types: ["house"],
    priceMin: 800_000,
    priceMax: 920_000,
    beds: 4,
    baths: 2,
    cars: 2,
    nice: ["ensuite", "ducted_heating_cooling"],
    breakers: ["main_road"],
  },
  {
    first: "Georgia",
    last: "Mainwaring",
    brief:
      "Under contract in Highton, settling in six weeks. Was a long search, good outcome.",
    status: "under_contract",
    finance: "pre_approved",
    timeframe: "now",
    source: "referral",
    contactedDaysAgo: 3,
    createdDaysAgo: 160,
    preApprovalInDays: 75,
    suburbs: ["Highton"],
    types: ["house"],
    priceMax: 950_000,
    beds: 4,
  },
  {
    first: "Ross",
    last: "Kilpatrick",
    brief:
      "Old enquiry, details incomplete. Was after something in Belmont. Nobody has called him.",
    status: "new_enquiry",
    finance: "unknown",
    timeframe: "unknown",
    source: "database_import",
    neverContacted: true,
    createdDaysAgo: 120,
    suburbs: ["Belmont"],
    types: ["house"],
    priceMax: 720_000,
  },
  {
    first: "Tanya",
    last: "Vukovic",
    partner: "Milos",
    brief:
      "Growing family, currently in a unit. Want a proper house with a yard for the dog. Not fussy on suburb, price drives it.",
    status: "looking",
    finance: "pre_approved",
    timeframe: "within_3_months",
    source: "open_home",
    contactedDaysAgo: 22,
    createdDaysAgo: 78,
    preApprovalInDays: 20,
    suburbs: ["Grovedale", "Belmont", "Armstrong Creek", "Leopold"],
    types: ["house"],
    priceMin: 620_000,
    priceMax: 780_000,
    beds: 3,
    baths: 1,
    cars: 2,
    landMin: 400,
    nice: ["side_access", "low_maintenance_yard"],
  },
  {
    first: "Benjamin",
    last: "Hollingsworth",
    brief:
      "Bought elsewhere, went with a new build at Armstrong Creek direct from the builder. Fair enough.",
    status: "bought_elsewhere",
    finance: "pre_approved",
    timeframe: "just_looking",
    source: "portal_enquiry",
    contactedDaysAgo: 44,
    createdDaysAgo: 190,
    suburbs: ["Armstrong Creek"],
    types: ["house"],
    priceMax: 700_000,
    beds: 4,
  },
  {
    first: "Ceylan",
    last: "Demirci",
    brief:
      "Investor, wants two more in the portfolio this year. Numbers driven, will move fast on the right thing. Also looking for a family home eventually.",
    status: "looking",
    finance: "cash",
    timeframe: "now",
    source: "referral",
    contactedDaysAgo: 9,
    createdDaysAgo: 64,
    suburbs: ["Belmont", "Grovedale", "Leopold"],
    types: ["unit", "townhouse"],
    priceMax: 580_000,
    beds: 2,
    baths: 1,
    nice: ["garage", "low_maintenance_yard"],
    breakers: ["needs_renovation"],
    second: {
      name: "Family home",
      suburbs: ["Highton", "Newtown"],
      types: ["house"],
      priceMin: 950_000,
      priceMax: 1_200_000,
      beds: 4,
      baths: 2,
      cars: 2,
      nice: ["ensuite", "study"],
    },
  },
  {
    first: "Melinda",
    last: "Ffrench-Davis",
    brief:
      "Not proceeding, her husband took a job in Brisbane. Was well advanced too. Disappointing.",
    status: "not_proceeding",
    finance: "pre_approved",
    timeframe: "just_looking",
    source: "open_home",
    contactedDaysAgo: 33,
    createdDaysAgo: 145,
    suburbs: ["Highton"],
    types: ["house"],
    priceMax: 950_000,
    beds: 4,
  },
  {
    first: "Josh",
    last: "Ballantyne",
    partner: "Em",
    brief:
      "Keen young couple, came to three opens in a row. Getting close to offering on something. Watch this space.",
    status: "inspecting",
    finance: "pre_approved",
    timeframe: "now",
    source: "open_home",
    contactedDaysAgo: 1,
    createdDaysAgo: 27,
    preApprovalInDays: 28,
    suburbs: ["Belmont", "Grovedale", "Highton"],
    types: ["house", "townhouse"],
    priceMin: 650_000,
    priceMax: 820_000,
    beds: 3,
    baths: 2,
    cars: 1,
    nice: ["renovated", "garage"],
  },
  {
    first: "Dimitri",
    last: "Panagopoulos",
    brief:
      "Settled in Waurn Ponds two months ago. Keep warm, he talks about investing later.",
    status: "purchased",
    finance: "pre_approved",
    timeframe: "just_looking",
    source: "walk_in",
    contactedDaysAgo: 29,
    createdDaysAgo: 270,
    suburbs: ["Waurn Ponds"],
    types: ["house"],
    priceMax: 850_000,
    beds: 4,
  },
  {
    first: "Imogen",
    last: "Ravensworth",
    brief:
      "Only wants acreage, something with a few acres for horses. Very specific and very patient. Will wait years if she has to.",
    status: "looking",
    finance: "cash",
    timeframe: "just_looking",
    source: "referral",
    contactedDaysAgo: 68,
    createdDaysAgo: 320,
    suburbs: ["Lara", "Drysdale"],
    types: ["acreage"],
    priceMin: 900_000,
    priceMax: 1_600_000,
    beds: 3,
    landMin: 20_000,
    must: ["shed_workshop"],
    nice: ["established_garden", "solar"],
  },
  {
    first: "Pauline",
    last: "Ackroyd",
    brief:
      "Long standing database contact, no recent activity. Was after a Belmont unit. Needs a proper check in, we don't even know if the number's current.",
    status: "looking",
    finance: "unknown",
    timeframe: "unknown",
    source: "database_import",
    contactedDaysAgo: 175,
    createdDaysAgo: 420,
    suburbs: ["Belmont", "Grovedale"],
    types: ["unit"],
    priceMax: 520_000,
    beds: 2,
  },
  {
    first: "Tobias",
    last: "Grieveson",
    brief:
      "Enquired on the Torquay listing. Wants coastal but his budget is Grovedale. Needs a gentle reality check.",
    status: "new_enquiry",
    finance: "not_started",
    timeframe: "within_6_months",
    source: "portal_enquiry",
    contactedDaysAgo: 12,
    createdDaysAgo: 16,
    suburbs: ["Torquay", "Ocean Grove"],
    also: ["Grovedale", "Armstrong Creek"],
    types: ["house", "townhouse"],
    priceMax: 700_000,
    beds: 3,
    nice: ["walk_to_beach"],
  },
  {
    first: "Renata",
    last: "Castellano",
    partner: "Paul",
    brief:
      "Downsizing but want to stay in Waurn Ponds near the golf course. Single level, two bedrooms plus a study for Paul's model trains. Low maintenance is the priority now.",
    status: "looking",
    finance: "cash",
    timeframe: "within_6_months",
    source: "walk_in",
    needsToSell: true,
    contactedDaysAgo: 37,
    createdDaysAgo: 155,
    suburbs: ["Waurn Ponds", "Highton"],
    types: ["house", "townhouse"],
    priceMin: 650_000,
    priceMax: 850_000,
    beds: 2,
    baths: 2,
    cars: 2,
    must: ["single_level", "low_maintenance_yard"],
    nice: ["study", "garage"],
    breakers: ["double_storey", "pool"],
  },
  {
    first: "Harold",
    last: "Beckinsale",
    brief:
      "Came in off the street about a year ago wanting something in Highton in the low nines. Nobody has spoken to him since. Either he's bought elsewhere or he's still waiting, and we look bad either way.",
    status: "looking",
    finance: "unknown",
    timeframe: "unknown",
    source: "walk_in",
    contactedDaysAgo: 132,
    createdDaysAgo: 360,
    suburbs: ["Highton", "Waurn Ponds"],
    types: ["house"],
    priceMin: 850_000,
    priceMax: 950_000,
    beds: 3,
    baths: 2,
    cars: 2,
    nice: ["garage", "single_level"],
  },
];

export const BUYER_SPECS: BuyerSpec[] = [
  ...GROUP_A_HIGHTON,
  ...GROUP_B_COASTAL,
  ...GROUP_C_ENTRY,
  ...GROUP_D_PREMIUM,
  ...GROUP_E_MIXED,
];

/* -------------------------------------------------------------------------
 * Properties
 * ---------------------------------------------------------------------- */

export type PropertySpec = {
  streetNumber: number;
  street: string;
  suburb: keyof typeof SUBURBS | string;
  type: PropertyType;
  status: ListingStatus;
  priceDisplay?: string;
  guideMin?: number;
  guideMax?: number;
  beds?: number;
  baths?: number;
  cars?: number;
  landSqm?: number;
  buildingSqm?: number;
  features: FeatureSlug[];
  description: string;
  /** Days ago this listing was added. Drives the "added this week" list. */
  addedDaysAgo: number;
};

export const PROPERTY_SPECS: PropertySpec[] = [
  /* ---- The hero off-market listing. ------------------------------------
   * Shaped to match well over ten of the Highton-corridor buyers with a
   * real spread of scores: dead-centre budgets, overlapping budgets,
   * stretch-only budgets, and buyers one bedroom short all land differently.
   * This is the listing to open in the demo.
   */
  {
    streetNumber: 18,
    street: "Kerrisdale Court",
    suburb: "Highton",
    type: "house",
    status: "off_market",
    priceDisplay: "Contact agent",
    guideMin: 880_000,
    guideMax: 950_000,
    beds: 4,
    baths: 2,
    cars: 2,
    landSqm: 620,
    buildingSqm: 232,
    features: [
      "ensuite",
      "study",
      "garage",
      "ducted_heating_cooling",
      "established_garden",
      "walk_to_school",
      "quiet_street",
      "side_access",
      "single_level",
    ],
    description:
      "Owners are testing the market before committing to a campaign. Single level four bedroom on a quiet court, walking distance to Montpellier Primary. Renovated kitchen and bathrooms, ducted heating and cooling throughout, established garden and side access to a double garage.",
    addedDaysAgo: 2,
  },

  /* ---- Other off-market listings. -------------------------------------- */
  {
    streetNumber: 7,
    street: "Somerville Grove",
    suburb: "Newtown",
    type: "house",
    status: "off_market",
    priceDisplay: "Contact agent",
    guideMin: 1_450_000,
    guideMax: 1_600_000,
    beds: 4,
    baths: 2,
    cars: 2,
    landSqm: 740,
    buildingSqm: 280,
    features: [
      "renovated",
      "established_garden",
      "north_facing",
      "quiet_street",
      "ensuite",
      "second_living",
      "study",
    ],
    description:
      "Restored Edwardian on a wide northerly block. The owners will sell quietly to the right buyer before Christmas.",
    addedDaysAgo: 5,
  },
  {
    streetNumber: 42,
    street: "Coledale Street",
    suburb: "Grovedale",
    type: "house",
    status: "off_market",
    // No price guide at all — this is the listing that shows the
    // "unknown" state on the fit strip.
    priceDisplay: "Contact agent",
    beds: 3,
    baths: 1,
    cars: 2,
    landSqm: 580,
    features: ["side_access", "shed_workshop", "needs_renovation", "corner_block"],
    description:
      "Deceased estate, family still deciding on price. Original condition throughout on a corner block with rear access. Nothing has been done to it in thirty years.",
    addedDaysAgo: 3,
  },

  /* ---- Pre-market listings. -------------------------------------------- */
  {
    streetNumber: 15,
    street: "Wattlebird Drive",
    suburb: "Armstrong Creek",
    type: "house",
    status: "pre_market",
    priceDisplay: "$640,000 - $690,000",
    guideMin: 640_000,
    guideMax: 690_000,
    beds: 4,
    baths: 2,
    cars: 2,
    landSqm: 448,
    buildingSqm: 186,
    features: [
      "garage",
      "ducted_heating_cooling",
      "low_maintenance_yard",
      "ensuite",
      "walk_to_school",
    ],
    description:
      "Four year old home in the Warralily estate. Photography booked for next week, campaign starts the week after.",
    addedDaysAgo: 4,
  },
  {
    streetNumber: 61,
    street: "Melrose Parade",
    suburb: "Ocean Grove",
    type: "house",
    status: "pre_market",
    priceDisplay: "$1,150,000 - $1,250,000",
    guideMin: 1_150_000,
    guideMax: 1_250_000,
    beds: 4,
    baths: 2,
    cars: 2,
    landSqm: 660,
    buildingSqm: 245,
    features: [
      "walk_to_beach",
      "north_facing",
      "renovated",
      "second_living",
      "home_office",
      "established_garden",
    ],
    description:
      "Coming to market shortly. A short walk to the surf beach, renovated with a separate home office at the rear.",
    addedDaysAgo: 6,
  },
  {
    streetNumber: 3,
    street: "Hollybank Place",
    suburb: "Waurn Ponds",
    type: "house",
    status: "pre_market",
    priceDisplay: "$820,000 - $880,000",
    guideMin: 820_000,
    guideMax: 880_000,
    beds: 4,
    baths: 2,
    cars: 2,
    landSqm: 592,
    buildingSqm: 210,
    features: [
      "study",
      "solar",
      "ducted_heating_cooling",
      "garage",
      "north_facing",
      "quiet_street",
    ],
    description:
      "Walking distance to Deakin. Solar, ducted heating and cooling, a dedicated study and a north facing living area.",
    addedDaysAgo: 1,
  },

  /* ---- On-market listings. --------------------------------------------- */
  {
    streetNumber: 29,
    street: "Tarrangower Street",
    suburb: "Belmont",
    type: "house",
    status: "on_market",
    priceDisplay: "Offers over $750,000",
    guideMin: 750_000,
    guideMax: 810_000,
    beds: 3,
    baths: 2,
    cars: 2,
    landSqm: 545,
    buildingSqm: 168,
    features: [
      "renovated",
      "garage",
      "walk_to_school",
      "walk_to_shops",
      "low_maintenance_yard",
    ],
    description:
      "Renovated throughout with a new kitchen and bathrooms. Walk to Belmont High and the High Street shops.",
    addedDaysAgo: 12,
  },
  {
    streetNumber: 88,
    street: "Ridgemont Avenue",
    suburb: "Highton",
    type: "house",
    status: "on_market",
    priceDisplay: "$1,050,000 - $1,150,000",
    guideMin: 1_050_000,
    guideMax: 1_150_000,
    beds: 5,
    baths: 3,
    cars: 2,
    landSqm: 780,
    buildingSqm: 310,
    features: [
      "pool",
      "second_living",
      "ensuite",
      "double_storey",
      "study",
      "ducted_heating_cooling",
      "established_garden",
    ],
    description:
      "Substantial double storey family home with a solar heated pool, two living areas and a dedicated study.",
    addedDaysAgo: 22,
  },
  {
    streetNumber: 12,
    street: "Pentland Rise",
    suburb: "Torquay",
    type: "house",
    status: "on_market",
    priceDisplay: "$1,250,000 - $1,375,000",
    guideMin: 1_250_000,
    guideMax: 1_375_000,
    beds: 4,
    baths: 2,
    cars: 2,
    landSqm: 512,
    buildingSqm: 228,
    features: [
      "walk_to_beach",
      "low_maintenance_yard",
      "north_facing",
      "renovated",
      "ensuite",
    ],
    description:
      "A short walk to the sand. Low maintenance coastal home with a north facing courtyard.",
    addedDaysAgo: 18,
  },
  {
    streetNumber: 54,
    street: "Yarrowee Street",
    suburb: "Geelong West",
    type: "house",
    status: "on_market",
    priceDisplay: "$880,000 - $950,000",
    guideMin: 880_000,
    guideMax: 950_000,
    beds: 3,
    baths: 1,
    cars: 1,
    landSqm: 420,
    buildingSqm: 145,
    features: [
      "walk_to_shops",
      "walk_to_station",
      "renovated",
      "established_garden",
      "corner_block",
    ],
    description:
      "Californian bungalow two streets back from Pakington Street. Renovated kitchen, original features retained.",
    addedDaysAgo: 9,
  },
  {
    streetNumber: 6,
    street: "Mirradong Way",
    suburb: "Lara",
    type: "house",
    status: "on_market",
    priceDisplay: "$680,000 - $730,000",
    guideMin: 680_000,
    guideMax: 730_000,
    beds: 4,
    baths: 2,
    cars: 4,
    landSqm: 812,
    buildingSqm: 196,
    features: [
      "shed_workshop",
      "side_access",
      "garage",
      "solar",
      "single_level",
      "walk_to_station",
    ],
    description:
      "Large block with a six by nine metre shed and full side access. Walk to Lara station.",
    addedDaysAgo: 15,
  },
  {
    streetNumber: 101,
    street: "Ferndale Road",
    suburb: "Belmont",
    type: "house",
    status: "on_market",
    priceDisplay: "$640,000 - $690,000",
    guideMin: 640_000,
    guideMax: 690_000,
    beds: 3,
    baths: 1,
    cars: 1,
    landSqm: 480,
    buildingSqm: 132,
    // On a main road on purpose, so the deal breaker rule is visible.
    features: ["main_road", "needs_renovation", "garage", "walk_to_shops"],
    description:
      "Solid brick home with scope to improve. Busy road position reflected in the price.",
    addedDaysAgo: 20,
  },
  {
    streetNumber: 24,
    street: "Kanooka Grove",
    suburb: "Leopold",
    type: "townhouse",
    status: "on_market",
    priceDisplay: "$545,000 - $575,000",
    guideMin: 545_000,
    guideMax: 575_000,
    beds: 3,
    baths: 2,
    cars: 1,
    landSqm: 232,
    buildingSqm: 138,
    features: ["garage", "low_maintenance_yard", "walk_to_shops", "renovated"],
    description:
      "Near new townhouse walking distance to Gateway Plaza. Ideal first home or investment.",
    addedDaysAgo: 11,
  },
  {
    streetNumber: 9,
    street: "Brightmore Street",
    suburb: "Newtown",
    type: "house",
    status: "on_market",
    priceDisplay: "Expressions of interest",
    // Deliberately no price guide — the "unknown" state again, this time
    // on a premium listing.
    beds: 4,
    baths: 2,
    cars: 2,
    landSqm: 695,
    buildingSqm: 265,
    features: [
      "renovated",
      "established_garden",
      "quiet_street",
      "north_facing",
      "ensuite",
      "study",
    ],
    description:
      "Expressions of interest closing in three weeks. Fully restored period home in one of Newtown's best streets.",
    addedDaysAgo: 7,
  },
  {
    streetNumber: 37,
    street: "Applegum Crescent",
    suburb: "Grovedale",
    type: "house",
    status: "on_market",
    priceDisplay: "$690,000 - $740,000",
    guideMin: 690_000,
    guideMax: 740_000,
    beds: 4,
    baths: 2,
    cars: 2,
    landSqm: 561,
    buildingSqm: 178,
    features: [
      "garage",
      "ducted_heating_cooling",
      "side_access",
      "low_maintenance_yard",
      "ensuite",
    ],
    description:
      "Four bedroom family home close to Grovedale College with side access for a caravan or boat.",
    addedDaysAgo: 14,
  },

  /* ---- Under offer. ----------------------------------------------------- */
  {
    streetNumber: 71,
    street: "Bellbrae Rise",
    suburb: "Ocean Grove",
    type: "house",
    status: "under_offer",
    priceDisplay: "$845,000",
    guideMin: 820_000,
    guideMax: 870_000,
    beds: 3,
    baths: 2,
    cars: 2,
    landSqm: 604,
    buildingSqm: 172,
    features: ["garage", "established_garden", "single_level", "walk_to_shops"],
    description: "Under offer after one weekend of inspections.",
    addedDaysAgo: 26,
  },
  {
    streetNumber: 4,
    street: "Marrandah Court",
    suburb: "Waurn Ponds",
    type: "house",
    status: "under_offer",
    priceDisplay: "$795,000",
    guideMin: 770_000,
    guideMax: 820_000,
    beds: 4,
    baths: 2,
    cars: 2,
    landSqm: 528,
    buildingSqm: 194,
    features: ["study", "garage", "ducted_heating_cooling", "quiet_street"],
    description: "Court location close to Deakin. Under offer, awaiting finance.",
    addedDaysAgo: 31,
  },
  {
    streetNumber: 50,
    street: "Lowanna Drive",
    suburb: "Armstrong Creek",
    type: "townhouse",
    status: "under_offer",
    priceDisplay: "$598,000",
    guideMin: 580_000,
    guideMax: 615_000,
    beds: 3,
    baths: 2,
    cars: 1,
    landSqm: 248,
    buildingSqm: 142,
    features: ["garage", "low_maintenance_yard", "ducted_heating_cooling"],
    description: "Under offer to a first home buyer.",
    addedDaysAgo: 29,
  },

  /* ---- Sold. ------------------------------------------------------------ */
  {
    streetNumber: 33,
    street: "Westbury Close",
    suburb: "Highton",
    type: "house",
    status: "sold",
    priceDisplay: "Sold $912,000",
    guideMin: 860_000,
    guideMax: 920_000,
    beds: 4,
    baths: 2,
    cars: 2,
    landSqm: 655,
    buildingSqm: 218,
    features: ["ensuite", "study", "garage", "established_garden", "quiet_street"],
    description: "Sold prior to auction after three days on market.",
    addedDaysAgo: 48,
  },
  {
    streetNumber: 17,
    street: "Sandalford Drive",
    suburb: "Torquay",
    type: "house",
    status: "sold",
    priceDisplay: "Sold $1,410,000",
    guideMin: 1_350_000,
    guideMax: 1_450_000,
    beds: 4,
    baths: 3,
    cars: 2,
    landSqm: 588,
    buildingSqm: 258,
    features: ["walk_to_beach", "pool", "second_living", "renovated", "ensuite"],
    description: "Sold at auction to a Melbourne buyer.",
    addedDaysAgo: 55,
  },
];
